openapi: 3.0.0
info:
  title: Dorsium RPC Gateway API
  version: 1.0.0
servers:
  - url: http://localhost:8080/api
paths:
  /:
    get:
      summary: Welcome message and API root
      responses:
        '200':
          description: Returns a welcome message
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  publicRoutes:
                    type: object
                    properties:
                      status:
                        type: string
                  documentation:
                    type: string
  /status:
    get:
      summary: Get system status
      responses:
        '200':
          description: System status response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  version:
                    type: string
                  timestamp:
                    type: string
                    format: date-time
                  mode:
                    type: string
